import { Bus, DriverProfile, Notice, Route, Schedule, Stop, StudentProfile, Trip, User } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    fullName: 'Dr. Alok Verma (Transport In-charge)',
    email: 'admin@university.edu',
    role: 'ADMIN',
    phone: '+91 98110 22334',
    isActive: true,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 2,
    fullName: 'Rajesh Kumar',
    email: 'driver1@university.edu',
    role: 'DRIVER',
    phone: '+91 98765 43210',
    isActive: true,
    createdAt: '2026-01-15T09:30:00Z',
  },
  {
    id: 3,
    fullName: 'Suresh Sharma',
    email: 'driver2@university.edu',
    role: 'DRIVER',
    phone: '+91 98765 43211',
    isActive: true,
    createdAt: '2026-01-16T10:00:00Z',
  },
  {
    id: 4,
    fullName: 'Vikram Singh',
    email: 'driver3@university.edu',
    role: 'DRIVER',
    phone: '+91 98765 43212',
    isActive: true,
    createdAt: '2026-01-18T10:00:00Z',
  },
  {
    id: 5,
    fullName: 'Priya Verma',
    email: 'student1@university.edu',
    role: 'STUDENT',
    phone: '+91 91234 56780',
    isActive: true,
    createdAt: '2026-02-01T11:00:00Z',
  },
  {
    id: 6,
    fullName: 'Rahul Mehra',
    email: 'student2@university.edu',
    role: 'STUDENT',
    phone: '+91 91234 56781',
    isActive: true,
    createdAt: '2026-02-02T11:00:00Z',
  },
  {
    id: 7,
    fullName: 'Ananya Sen',
    email: 'student3@university.edu',
    role: 'STUDENT',
    phone: '+91 91234 56782',
    isActive: true,
    createdAt: '2026-02-03T11:00:00Z',
  },
];

export const INITIAL_DRIVERS: DriverProfile[] = [
  {
    id: 1,
    userId: 2,
    licenseNumber: 'DL-042020-009811',
    experienceYears: 8,
    assignedBusId: 1,
  },
  {
    id: 2,
    userId: 3,
    licenseNumber: 'DL-042018-004455',
    experienceYears: 6,
    assignedBusId: 2,
  },
  {
    id: 3,
    userId: 4,
    licenseNumber: 'DL-042015-001290',
    experienceYears: 11,
    assignedBusId: 3,
  },
];

export const INITIAL_STUDENTS: StudentProfile[] = [
  {
    id: 1,
    userId: 5,
    rollNumber: '2023CSB101',
    department: 'Computer Science & Engg',
    semester: 'Semester 6',
    preferredStopId: 3,
  },
  {
    id: 2,
    userId: 6,
    rollNumber: '2023ECB145',
    department: 'Electronics & Comm.',
    semester: 'Semester 4',
    preferredStopId: 5,
  },
  {
    id: 3,
    userId: 7,
    rollNumber: '2024MEB210',
    department: 'Mechanical Engg',
    semester: 'Semester 2',
    preferredStopId: 8,
  },
];

export const INITIAL_STOPS: Stop[] = [
  {
    id: 1,
    stopName: 'University Main Gate (Campus Hub)',
    latitude: 28.4595,
    longitude: 77.0266,
    landmark: 'Administrative Block North',
  },
  {
    id: 2,
    stopName: 'Sector 14 Market Crossing',
    latitude: 28.4715,
    longitude: 77.0392,
    landmark: 'Opposite Community Center',
  },
  {
    id: 3,
    stopName: 'Civil Lines Bus Stand',
    latitude: 28.4632,
    longitude: 77.0498,
    landmark: 'Near District Court',
  },
  {
    id: 4,
    stopName: 'City Center Metro Station',
    latitude: 28.4590,
    longitude: 77.0725,
    landmark: 'Gate No. 2 Metro Parking',
  },
  {
    id: 5,
    stopName: 'Cyber Park Tech Hub',
    latitude: 28.4502,
    longitude: 77.0580,
    landmark: 'Tower B Main Drop Point',
  },
  {
    id: 6,
    stopName: 'Sushant Lok Phase 1',
    latitude: 28.4688,
    longitude: 77.0850,
    landmark: 'Near Vyapar Kendra',
  },
  {
    id: 7,
    stopName: 'Old Railway Station Terminal',
    latitude: 28.4795,
    longitude: 77.0120,
    landmark: 'Platform 1 Footbridge',
  },
  {
    id: 8,
    stopName: 'Model Town Circle',
    latitude: 28.4850,
    longitude: 77.0215,
    landmark: 'Clock Tower Junction',
  },
];

export const INITIAL_ROUTES: Route[] = [
  {
    id: 1,
    routeCode: 'R-01',
    routeName: 'Main Campus ↔ City Center Metro',
    origin: 'University Main Gate',
    destination: 'City Center Metro Station',
    approxDurationMinutes: 35,
    isActive: true,
    stops: [
      { id: 1, routeId: 1, stopId: 1, stopSequence: 1, estimatedMinutesFromStart: 0, stop: INITIAL_STOPS[0] },
      { id: 2, routeId: 1, stopId: 2, stopSequence: 2, estimatedMinutesFromStart: 12, stop: INITIAL_STOPS[1] },
      { id: 3, routeId: 1, stopId: 3, stopSequence: 3, estimatedMinutesFromStart: 22, stop: INITIAL_STOPS[2] },
      { id: 4, routeId: 1, stopId: 4, stopSequence: 4, estimatedMinutesFromStart: 35, stop: INITIAL_STOPS[3] },
    ],
  },
  {
    id: 2,
    routeCode: 'R-02',
    routeName: 'Main Campus ↔ Cyber Park & Sushant Lok',
    origin: 'University Main Gate',
    destination: 'Sushant Lok Phase 1',
    approxDurationMinutes: 45,
    isActive: true,
    stops: [
      { id: 5, routeId: 2, stopId: 1, stopSequence: 1, estimatedMinutesFromStart: 0, stop: INITIAL_STOPS[0] },
      { id: 6, routeId: 2, stopId: 5, stopSequence: 2, estimatedMinutesFromStart: 20, stop: INITIAL_STOPS[4] },
      { id: 7, routeId: 2, stopId: 6, stopSequence: 3, estimatedMinutesFromStart: 45, stop: INITIAL_STOPS[5] },
    ],
  },
  {
    id: 3,
    routeCode: 'R-03',
    routeName: 'Main Campus ↔ Railway Station Terminal',
    origin: 'University Main Gate',
    destination: 'Old Railway Station Terminal',
    approxDurationMinutes: 30,
    isActive: true,
    stops: [
      { id: 8, routeId: 3, stopId: 1, stopSequence: 1, estimatedMinutesFromStart: 0, stop: INITIAL_STOPS[0] },
      { id: 9, routeId: 3, stopId: 8, stopSequence: 2, estimatedMinutesFromStart: 15, stop: INITIAL_STOPS[7] },
      { id: 10, routeId: 3, stopId: 7, stopSequence: 3, estimatedMinutesFromStart: 30, stop: INITIAL_STOPS[6] },
    ],
  },
];

export const INITIAL_BUSES: Bus[] = [
  {
    id: 1,
    busNumber: 'MRU-101',
    registrationPlate: 'DL-01-EQ-1044',
    capacity: 52,
    status: 'ACTIVE',
    currentRouteId: 1,
    assignedDriverId: 1,
  },
  {
    id: 2,
    busNumber: 'MRU-102',
    registrationPlate: 'DL-01-EQ-1045',
    capacity: 52,
    status: 'ACTIVE',
    currentRouteId: 2,
    assignedDriverId: 2,
  },
  {
    id: 3,
    busNumber: 'MRU-103',
    registrationPlate: 'DL-01-EQ-1046',
    capacity: 48,
    status: 'ACTIVE',
    currentRouteId: 3,
    assignedDriverId: 3,
  },
  {
    id: 4,
    busNumber: 'MRU-104',
    registrationPlate: 'DL-01-EQ-1047',
    capacity: 50,
    status: 'MAINTENANCE',
    currentRouteId: undefined,
  },
  {
    id: 5,
    busNumber: 'MRU-105',
    registrationPlate: 'DL-01-EQ-1048',
    capacity: 55,
    status: 'ACTIVE',
    currentRouteId: 1,
  },
];

export const INITIAL_SCHEDULES: Schedule[] = [
  {
    id: 1,
    routeId: 1,
    busId: 1,
    departureTime: '07:45 AM',
    shift: 'MORNING',
    daysOfOperation: 'Mon - Fri',
    isActive: true,
  },
  {
    id: 2,
    routeId: 2,
    busId: 2,
    departureTime: '08:00 AM',
    shift: 'MORNING',
    daysOfOperation: 'Mon - Fri',
    isActive: true,
  },
  {
    id: 3,
    routeId: 3,
    busId: 3,
    departureTime: '08:15 AM',
    shift: 'MORNING',
    daysOfOperation: 'Mon - Fri',
    isActive: true,
  },
  {
    id: 4,
    routeId: 1,
    busId: 1,
    departureTime: '04:30 PM',
    shift: 'EVENING',
    daysOfOperation: 'Mon - Fri',
    isActive: true,
  },
  {
    id: 5,
    routeId: 2,
    busId: 2,
    departureTime: '05:00 PM',
    shift: 'EVENING',
    daysOfOperation: 'Mon - Fri',
    isActive: true,
  },
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 1,
    scheduleId: 1,
    busId: 1,
    driverId: 1,
    routeId: 1,
    tripStatus: 'ON_ROUTE',
    currentStopId: 2,
    startedAt: '2026-10-08T07:45:00Z',
    remarks: 'Departed on time. Normal campus traffic.',
  },
  {
    id: 2,
    scheduleId: 2,
    busId: 2,
    driverId: 2,
    routeId: 2,
    tripStatus: 'ON_ROUTE',
    currentStopId: 5,
    startedAt: '2026-10-08T08:00:00Z',
    remarks: 'Moderate traffic near Cyber Hub flyover.',
  },
  {
    id: 3,
    scheduleId: 3,
    busId: 3,
    driverId: 3,
    routeId: 3,
    tripStatus: 'SCHEDULED',
    currentStopId: 1,
    remarks: 'Parked at University Gate. Awaiting departure.',
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 1,
    title: 'Mid-Term Exam Special Bus Timings Notice',
    content: 'Special return buses will depart at 01:30 PM and 05:15 PM during the upcoming examination week across Routes R-01 and R-02.',
    category: 'GENERAL',
    publishedBy: 'Transport Department',
    createdAt: '2026-10-06T09:00:00Z',
    isActive: true,
  },
  {
    id: 2,
    title: 'Route R-01 Temporary Diversion at Civil Lines',
    content: 'Due to municipal road maintenance near Civil Lines Court, MRU-101 will stop 100 meters ahead near the City Post Office.',
    category: 'ROUTE_CHANGE',
    publishedBy: 'Fleet Supervisor',
    createdAt: '2026-10-07T14:30:00Z',
    isActive: true,
  },
  {
    id: 3,
    title: 'Monsoon Safety Protocol & Speed Regulations',
    content: 'All university drivers are advised to maintain a strict speed limit of 35 km/h within campus roads and 45 km/h on highway sectors.',
    category: 'GENERAL',
    publishedBy: 'Admin Office',
    createdAt: '2026-10-04T10:00:00Z',
    isActive: true,
  },
];
